### ISSUE TITLE
Bat To Exe Converterのコマンドライン引数について

### ISSUE THREAD

**Issue by 3223779RC** [nodai2hITC/neri#1]
F2KO氏のサイトにあるバージョン3.0.6.0ではコマンドライン引数は
/bat <filename> /exe <filename> `/'から始まるその他のオプション
となっており、build.rbを書き換えなくてはexeファイルの作成に失敗してしまいます。
NeriではどのバージョンのBat To Exe Converterを使用することを想定していますか？

**Comment by nodai2hITC** [comment]
気付くのが遅れてしまって申し訳ありません。
私の方で使っていたのは 2.4.8 でしたが、いつの間にか互換性のないメジャーバージョンアップが行われていたんですね。
古いバージョンはダウンロードできないようですから新しいものに対応すべきかと思いますので、バージョン 3 に対応した新しいものをリリースしました。
ご報告ありがとうございました。
