### ISSUE TITLE
ridk enable の記載例があるとありがたい件

### ISSUE THREAD

**Issue by masa-kunikata** [nodai2hITC/neri#3]
こんにちは。neri ありがたく、使用させていただいております。

日本語の説明文
neri/README.ja.md 

> Ruby の拡張ライブラリをコンパイルできる環境ならばおそらく大丈夫。

この部分、自分の環境では、
「拡張ライブラリは、コンパイルできているんで、大丈夫だろう」
と思ってたんですが、
RubyInstaller でインストール時にセットされる PATH だけでは、gcc などにパスが通ってない状態のようで、neriの作業するコマンドプロンプトで

```
ridk enable
```

とする必要がありました。

（参考）
https://github.com/oneclick/rubyinstaller2/wiki/The-ridk-tool#ridk-enable--disable

---

自分の環境が特殊なだけかもしれないんですが、
RubyInstallerインストール時の、動作環境として、```ridk enable``` が記載されていると
ありがたいかもしれんです～

**Comment by nodai2hITC** [comment]
ご指摘ありがとうございます。README.ja.md を書き換えさせてもらいました。
私自身は RubyInstaller をトリッキーな方法で入れていたもので、まったくそのことに気付いておりませんでした。今後とも何かあればご指摘お願いします。
