### ISSUE TITLE
datファイル内を相対パスで参照するとエラーが起きて参照できない

### ISSUE THREAD

**Issue by fujimurakengo** [nodai2hITC/neri#5]
先日は対応いただきありがとうございました。
まだ不具合があったので報告します。

タイトルの通りですが、ファイルや画像を読み込むときに絶対パスでなく相対パスで記述している場合に.datファイル内を参照できずにエラーで落ちる問題です。

neriでexe(bat)ファイルを作成する際コマンドライン引数で　../*　などでdata.datファイルを作成した際などに発生します。
"../gazou/gazou.png"のようなパスでデータを参照しようとすると、datファイル内では"D:\fuga\hoge\aaa\file\gazou\gazou.png"をキーとしてあるのでdatファイルを参照できずにdatの外を参照してエラーになります。

解決策としてneriを作成した際のカレントディレクトリパスをexe内などに保持しておき、ファイル参照が起こった際に
参照したいパスが絶対参照か相対参照か判断し、相対参照ならばexe内のカレントディレクトリパスと結合させてdat内を参照するようにすることで解決できると思います。
ファイルパスの結合にはPathnameクラスを利用すると簡単に結合できます。

ただ現状単純に上の実装をしてしまうと問題があります。neriでexe化したファイルと同じ階層にある.rbファイルは"hoge.rb"というキーを持っています。キーが絶対パスではありません。そのため常に絶対パス参照にするとhoge.rbが参照できなくなってしまいます。そのため同じ階層にある.rbファイルなどもdat内で絶対パスのキーを持つようにしたら良いと思うのですがどうでしょうか

**Comment by nodai2hITC** [comment]
なるほど、確かにその通りでした。報告ありがとうございます。

解決策も提案していただきましたが、キーを（作成した際の）絶対パスにするのは場所を移動してしまうと動かなくなるため避けたいところなので、以下のような対応を考えています。

- dat ファイル内では、できるだけ相対パスでキーを保存しておく。
- dat ファイルが読み込まれた際に、キーをすべて実行時のカレントディレクトリをもとに絶対パスに変換する。
- アクセスの際には、相対パスも絶対パスに変換して参照する。

**Comment by fujimurakengo** [comment]
キーを（作成した際の）絶対パスにするのは場所を移動してしまうと動かなくなる
今の状態でキーが（作成した際の）絶対パスになっているデータがほとんどです。確認してみてください。今の状態でもファイルの場所を動かしてもキーとして使っているパスさえ正しければ動くようになっています。なので気にしなくてもよいと思います。

最初に投稿したのにも書いてますがneriを作成した際のカレントディレクトリパスをexe内などに定数として保存しておきます。この定数と相対参照のパスを連結することで仮想的にどこのファイルでも最初にneriを実行したパスでdat内参照ができます。（runtime.rb 23行目の @datafileと相対ファイルパスを結合しろと言ってるわけじゃないですよ）パスをキーとして使っているだけなのでどのパソコンに動かそうがキーはキーなのでdat内を参照できます。なので相対パスにしなくてもよいと思います。

exeファイル内に実行時のカレントディレクトリパスを保持しておくのが問題であるならばexeに変換する際、絶対参照をしているデータをすべて相対参照に書き換えた上でdat内の参照キーをすべて相対パスで記述する方もよいともいます。

**Comment by nodai2hITC** [comment]
なんとなく「絶対パスにすると動かなくなる」と思い込んでいましたが、確かに言われてみればキーとパスが一致さえすれば絶対パスでも問題ない（むしろ相対パスより確実）ですね。

…ですが、そこでキーを絶対パスにすることについて改めて考えてみたところ、別の問題点が思い浮かびました。絶対パスになると意図せずに自分の開発場所のパスを漏洩させてしまう可能性があります。（たとえばホームディレクトリ以下で開発している場合は多いと思いますが、その場合ユーザー名がパスに含まれています。ユーザー名が本名だった場合、それを知られてしまう可能性があります。）

そう考えると `../*` でキーが絶対パスになってしまうのは危険なバグなので修正したいと思います。また、相対パスでも基本的に問題なく動くように修正したいと思いますが、絶対パスのほうが確実性があることも分かったので、「意図的に絶対パスを引数に与えた際は絶対パスを、相対パスを与えた場合は相対パスをキーとして保存する」といった形にしようかと思っています。

**Comment by nodai2hITC** [comment]
遅くなりましたが、修正版 0.9.3 をリリースしました。よろしければ動作確認していただけると幸いです。

**Comment by fujimurakengo** [comment]
nodai2hITCさん修正お疲れさまでした。
すいませんがまた不具合を発見してしまいました。
特定のファイルを参照できないﾊﾞｸﾞです。

**発生状況**
D:/user/fujimura/programfiles
                      /src
                     　　　　/main.rb
                     　　　　/sub.rb
                      /data
                      /bgm
という構造のファイルがあり、/srcにはプログラムのソースmain,subが入っています。
D:/user/fujimura/programfiles/srcで
neri　main.rb ../* --no-exe
を実行して生成したファイルを用いるのが発生状況です。

**ﾊﾞｸﾞの内容**
今回のﾊﾞｸﾞでは
main.rbとおなじファイルに入っているプログラムsub1.rbが参照できません。
発生タイミングは
main.rb
から
require './sub1.rb'
を実行したときです。

調べたところsub1.rbは@filesの中に../src/sub1.rbをkeyとして存在してます。
これだとrequire './sub1.rb'で参照できません。
これが原因だと思われます

**解決方法の提案**
いろいろ考えたのですが結構根が深いようなと考えています。
多少手戻りがあるのですが

仮想的なファイルパスを用意しそこからの相対パス参照にすると解決できるかと思います。
どういうことかと言うと
今回の実装の変更の理由のついに
D:/user/fujimura/programfiles/src
というファイルパスで実行すると@fileの中にfujimuraという作成者の名前が見えてしまうからですよね。
このうち
D:/user/fujimura/programfilesまでを
neri_virtual_filepathと置き換えてファイルパスを
neri_virtual_filepath/src
として扱うようにします。
今までに近いような手法ですが、@file内ではneri_virtual_filepath/src/sub1.rb
として扱うようにします。
これだとrequire './sub1.rb'で参照するときに
私の大好きなpathnameを使って
neri_virtual_filepath/srcと./sub1.rbを足し合わせるようにします。
neri_virtual_filepath/src/sub1.rbとして@file内を参照するので
これで問題が解決できるかと思います。

この方法だとほかにも
../src/../src/sub1.rb
みたいなふざけた参照をされたとしても問題が発生しません。
また、セキュリティを気にしない場合に限りますが
neri_virtual_filepathをneri実行時に任意の文字列に変更できるようにする
例えばD:/user/fujimura/programfiles
にできるようにすることで
require 'D:/user/fujimura/programfiles/sub1.rb'
みたいな参照をしているプログラムでも動くようになります。
本当にセキュリティを気にしないようにする場合だけですが。

以上の手法で解決できると思うのですがどうでしょうか

**Comment by nodai2hITC** [comment]
報告ありがとうございます。どうも自分で使っているだけだと特定のフォルダ構成上での動作しかテストできていなかったので、こうして他の人に実際に使っていただけると色々気付かされて参考になります。

とりあえず @fujimurakengo さんの案を参考に、修正方法を検討してみます。

**Comment by nodai2hITC** [comment]
ちょっと本格的な修正は骨が折れそうだったので、とりあえず簡易的に修正して 0.9.4 をリリースしました。（後でもっと根本的な修正をできればと思ってます。）

具体的には、カレントディレクトリ以下のファイルは、上の例で言えばキーを`../src/sub1.rb`だけではなく`./sub1.rb`という形でも持つようにしました。これではうまく行かないケースも有ることにはすでに気づいてはいるのですが（たとえばキーが`../../aaa/bbb/ccc.rb`+`./ccc.rb`という形で保持されている状況で、`../bbb/ccc.rb`というパス指定でロードするなど。）だいたいのケースではこれでも動作するのではないかと思います。

**Comment by fujimurakengo** [comment]
お疲れ様です
プルリクの方に解決案投げたのでよろしければ参考にして下さい

**Comment by nodai2hITC** [comment]
PR を参考に修正をしてみました。
Pathname はあまり使ったことが無かったので PR がたいへん参考になりました。ありがとうございます。

@fujimurakengo さん提案の仮想的なファイルパスを使う方法を取り入れましたが、それだけではなく従来の実行時のカレントディレクトリからのフルパスを使う方法も併用しています。前者のほうがいろいろなケースに対応できそうなのですが、カレントディレクトリをプログラム内で動かした場合への対応が難しく、後者ならそれにも簡単に対応できるためです。「ありとあらゆるケースに対応」とまでは言えませんが、ほとんどの一般的なケースには対応できるようになったのではないかと思います。

**Comment by nodai2hITC** [comment]
Open のまま放置するのも良くないので、 Close させていただきます。
